### ISSUE TITLE
Options for alternative authentication

### ISSUE THREAD

**Issue by donjuanmon** [hamletmun/PSRedmine#1]
My Redmine instance lives behind shibboleth. Options for connecting via API would be greatly appreciated. Great work so far!

https://www.redmine.org/projects/redmine/wiki/rest_api#Authentication

**Comment by hamletmun** [comment]
Years ago the API Key was hardcoded in **Send-HTTPRequest** and then moved to a psd configuration file with the server url.

```powershell
Function Send-HTTPRequest {
...
    $IRMParams = @{
        Headers = @{ 'X-Redmine-API-Key' = '0123456789abcdef0123456789abcdef01234567' }
        Method = $Method
        Uri = $script:Server + $Uri
    }
...
}
```

**Comment by donjuanmon** [comment]
Hey @hamletmun,

Thanks, I actually got this implemented a while ago and have been using this module in my scripts for a few months. 

```
    $IRMParams = @{
        #WebSession = $script:WebSession
        Headers = @{ "X-Redmine-API-Key" = $script:API }
        Method = $Method
        Uri = $script:Server + $Uri
    }
```

I call the API string from an encrypted file to keep safe. Cheers and thanks for the great work!

**Comment by hamletmun** [comment]
cb0b3667678d213b58673bf7a4c4c3d6d854269a adds API Key param to Connect-Redmine
