### ISSUE TITLE
API Authentification would be helpful 

### ISSUE THREAD

**Issue by hriess** [hamletmun/PSRedmine#3]
See redmine Website

Most of the time, the API requires authentication. To enable the API-style authentication, you have to check Enable REST API in Administration -> Settings -> API. Then, authentication can be done in 2 different ways:
using your regular login/password via HTTP Basic authentication.
using your API key which is a handy way to avoid putting a password in a script. The API key may be attached to each request in one of the following way:
passed in as a "key" parameter
passed in as a username with a random password via HTTP Basic authentication
passed in as a "X-Redmine-API-Key" HTTP header (added in Redmine 1.1.0)
You can find your API key on your account page ( /my/account ) when logged in, on the right-hand pane of the default layout.

this type of authentification allows creation of scripts without Manual entering User / Passwort

**Comment by hamletmun** [comment]
See #1
