### ISSUE TITLE
During login: InvalidOperation: Cannot index into a null array 

### ISSUE THREAD

**Issue by majkinetor** [hamletmun/PSRedmine#4]
Its because Forms here doesn't exist

```ps1
	Hidden signin($IWRParams) {.
                ...
		$this.CSRFToken = $Response.Forms.Fields['authenticity_token']
```

**Comment by majkinetor** [comment]
It works if I just remove this line.

**Comment by hamletmun** [comment]
Any information about your environment?

Maybe you set `allow_forgery_protection = false` to disable [CSRF](https://en.wikipedia.org/wiki/Cross-site_request_forgery "Cross-Site Request Forgery") token?

**Comment by majkinetor** [comment]
Latest Redmine, I don't know about the setting.
